from typing import TypedDict, Optional, List, Dict, Any, Annotated
from langgraph.graph.message import add_messages


class TeamState(TypedDict):
    """
    Global state object passed across all specialized agent nodes in LangGraph.
    """
    project_id: str
    user_idea: str
    preferred_tech: Optional[str]
    
    # Artifact outputs generated by specialized agents
    scope: Optional[Dict[str, Any]]
    requirements: Optional[Dict[str, Any]]
    architecture: Optional[Dict[str, Any]]
    
    # Reviewer and Human-in-the-loop fields
    reviewer_feedback: Optional[str]
    approval_status: str  # PENDING, APPROVED, REJECTED, REVISION_REQUESTED
    current_agent: str
    revision_count: int
    
    # LangGraph conversation history
    messages: Annotated[List[Dict[str, Any]], add_messages]
